### ISSUE TITLE
README.md: remove references to py2, put conda commands in text

### ISSUE THREAD

**Issue by chunhochow** [dlab-berkeley/Geospatial-Fundamentals-in-Python#3]
1. Remove most references to py2 in 1.1 Download Anaconda
(and remove the `#windowsDownload` in the https://www.anaconda.com/distribution/#windowsDownload link)
2. the conda commands in second to last section: just put the text in rather than use the geopandas manual screenshot

**Comment by hikari-murayama** [comment]
Thanks @chunhochow 🥇
