### ISSUE TITLE
Broken link in interactive map example (Notebook 10)

### ISSUE THREAD

**Issue by brooksjessup** [dlab-berkeley/Geospatial-Fundamentals-in-Python#6]
In notebook 10 at end of section 10.1, the interactive map example has a broken link (bartmap_example.html). See my screenshot attached.
<img width="1176" alt="Screen Shot 2021-01-13 at 8 40 29 PM" src="https://user-images.githubusercontent.com/62086981/104546053-37139e80-55e0-11eb-8ef6-9cc7ac0f3d8a.png">

**Comment by hikari-murayama** [comment]
This issue was resolved with commit 6ae8f5aa00cfb8cd6b158eb377d4da922c08ff8b
